name = "my-worker"
main = "src/index.ts"
compatibility_date = "2023-04-03"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "quotes_db"
database_id = "your-database-id"  # Replace with your actual database ID if known, otherwise it will be created on first deploy

[vars]
AUTH0_DOMAIN = "your-auth0-domain"
AUTH0_AUDIENCE = "your-api-identifier"
AUTH0_ADMIN_ROLE = "admin" # Claim name for admin role in JWT
