name: Demo Deployment

on:
  workflow_dispatch:

jobs:
  e2e-tests-consumer:
    name: "E2E Tests - Consumer App"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: ./test/e2e-tests/package-lock.json
      - name: Install dependencies (E2E tests)
        run: |
          cd test/e2e-tests
          npm install
      - name: Setup Playwright
        run: |
          cd test/e2e-tests
          npx playwright install chromium
      - name: Run E2E tests
        env:
          CONSUMER_BASE_URL: "https://random-quotes.javiercaballero.info/"
        run: |
          cd test/e2e-tests
          npm run test-consumer
      - name: Upload results
        uses: actions/upload-artifact@v4
        if: ${{ failure() || cancelled() }}
        with:
          name: playwright-report-consumer
          path: test/e2e-tests/playwright-report/
          retention-days: 30
