name: Production Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-server:
    name: "Deploy - Server"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: ./server/package-lock.json
      - name: Deploy Server to Cloudflare
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4.12.0"
          workingDirectory: "./server"
          command: deploy
  deploy-client-admin:
    name: "Deploy - Client Admin"
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./client/admin
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: ./client/admin/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        env:
          VITE_API_URL: ${{ secrets.API_URL }}
          VITE_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        run: npm run build
      - name: Deploy Client to Cloudflare
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4.12.0"
          workingDirectory: "./client/admin"
          command: pages deploy
  deploy-client-consumer:
    name: "Deploy - Client Consumer"
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./client/consumer
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: ./client/consumer/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        env:
          VITE_DATA_API: ${{ secrets.API_URL }}
        run: npm run build
      - name: Deploy Client to Cloudflare
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4.12.0"
          workingDirectory: "./client/consumer"
          command: pages deploy
